MAGNIT_API_HOST = 'web-gateway.middle-api.magnit.ru'
MAGNIT_API_PROMOTIONS_PATH = 'v1/promotions'
MAGNIT_API_PROMOTIONS_URL = f'https://{MAGNIT_API_HOST}/{MAGNIT_API_PROMOTIONS_PATH}'

CARD_PROMOTIONS_CATEGORY_ID = '150'

